### ISSUE TITLE
Quick-start example lacks some import statement

### ISSUE THREAD

**Issue by haesleinhuepf** [mapmanager/brightest-path-lib#43]
Hi all,

I was just trying to execute the [quick start](https://mapmanager.net/brightest-path-lib/quickstart_guide/) example and retrieve an error in the second code cell.

code:
```
start = np.array([0,192])
goal = np.array([198,9])
```

Error:;
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 start = np.array([0,192])
      2 goal = np.array([198,9])

NameError: name 'np' is not defined
```

I recommend:
* Adding the `import numpy as np` statement to the example.
* Provide the example as notebook users can download and execute. We don't have to copy&paste it line by line then ;-)

Thanks!

Bestt,
Robert

**Comment by cudmore** [comment]
Thanks for the feedback and tips. We have switched the quickstart to a Jupyter notebook so users can download and run and have added  `import numpy as np` to the notebook. All as you kindly suggested!
