### ISSUE TITLE
Consider adding __version__

### ISSUE THREAD

**Issue by haesleinhuepf** [mapmanager/brightest-path-lib#45]
... as recommended in [this blog post](https://martin-thoma.com/python-package-versions/) to the [__init__.py](https://github.com/mapmanager/brightest-path-lib/blob/main/brightest_path_lib/__init__.py). This would make it easy for end-users to figure and/or document out the current verrsion of the library.

**Comment by cudmore** [comment]
Thanks for the recommendation, we have added a `__version__` string. It can be used like so:

```
import brightest_path_lib
print(brightest_path_lib.__version__)
```
