### ISSUE TITLE
something wrong in quick-start

### ISSUE THREAD

**Issue by LeviZhang1996** [mapmanager/brightest-path-lib#46]
Hi there,I am try your lib by the quick-start.I got some trouble.
First,ski-image ask module pooch for downloading images.Of course,it's easy to solve.
Secondly,I copied the quick-start code to my jupyter,then got error below:
![image](https://github.com/mapmanager/brightest-path-lib/assets/83460341/3ccd2332-4f3f-4f6a-b75d-50f173a4cfe4)
'end' alter to 'goal' works.
![img_v2_825be241-afd6-4b6b-ad51-074d9eb58dfg](https://github.com/mapmanager/brightest-path-lib/assets/83460341/bd7f32d0-1ea6-4a69-958f-6c19ded764d9)

**Comment by cudmore** [comment]
Thanks for the feedback and sorry  for the late response. We fixed the above two errors.
